// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CefUnity
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "cef_unity_rust";





        /// <summary>
        ///  Initialize: launch CEF server process and connect via ipc-channel.
        ///  Returns 0 on success, non-zero on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_init();

        /// <summary>
        ///  Pump CEF message loop — no-op in IPC mode (server has its own loop).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_pump", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_pump();

        /// <summary>
        ///  Returns the number of on_paint calls (tracked per-frame reads in IPC mode).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_paint_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_paint_count();

        /// <summary>
        ///  Returns the number of pump iterations.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_pump_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_pump_count();

        /// <summary>
        ///  Shut down: send Shutdown command and wait for server to exit.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_shutdown();

        /// <summary>
        ///  Create a browser instance via IPC.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_create_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CefUnityBrowser* cef_unity_create_browser(int width, int height, byte* url);

        /// <summary>
        ///  Destroy a browser instance.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_destroy_browser(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_load_url(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_resize(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Send a mouse move event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_move", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_move(CefUnityBrowser* handle, int x, int y, uint modifiers);

        /// <summary>
        ///  Send a mouse click event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_click", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_click(CefUnityBrowser* handle, int x, int y, uint modifiers, byte button, int mouse_up, int click_count);

        /// <summary>
        ///  Send a mouse wheel event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_wheel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_wheel(CefUnityBrowser* handle, int x, int y, uint modifiers, int delta_x, int delta_y);

        /// <summary>
        ///  Send a key event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_key_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_key_event(CefUnityBrowser* handle, byte event_type, uint modifiers, int windows_key_code, int native_key_code, ushort character, ushort unmodified_character, int is_system_key, int focus_on_editable_field);

        /// <summary>
        ///  Execute JavaScript in the browser's main frame.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_execute_javascript", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_execute_javascript(CefUnityBrowser* handle, byte* code);

        /// <summary>
        ///  Get the browser's current main-frame URL as UTF-8 bytes.
        ///  Returns the required buffer size including the trailing NUL terminator.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_url(CefUnityBrowser* handle, byte* buffer, int buffer_len);

        /// <summary>
        ///  Get the latest frame buffer from shared memory.
        ///  Returns 1 if a new frame is available, 0 if unchanged.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_buffer(CefUnityBrowser* handle, byte** out_buffer, int* out_width, int* out_height);

        /// <summary>
        ///  Destroy a browser instance (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_destroy_browser_blocking(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_load_url_blocking(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_resize_blocking(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Send a mouse move event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_move_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_move_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers);

        /// <summary>
        ///  Send a mouse click event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_click_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_click_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers, byte button, int mouse_up, int click_count);

        /// <summary>
        ///  Send a mouse wheel event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_wheel_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_wheel_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers, int delta_x, int delta_y);

        /// <summary>
        ///  Send a key event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_key_event_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_key_event_blocking(CefUnityBrowser* handle, byte event_type, uint modifiers, int windows_key_code, int native_key_code, ushort character, ushort unmodified_character, int is_system_key, int focus_on_editable_field);

        /// <summary>
        ///  Execute JavaScript in the browser's main frame (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_execute_javascript_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_execute_javascript_blocking(CefUnityBrowser* handle, byte* code);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CefUnityBrowser
    {
        public byte _opaque;
    }



}
