// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CefUnity
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "cef_unity_rust";





        /// <summary>
        ///  Initialize: launch CEF server process and connect via ipc-channel.
        ///  `use_gpu`: 非 0 で accelerated paint (GPU 共有テクスチャ / IOSurface) を使う。
        ///  0 で software paint (CPU 経由の shm BGRA 転送) を強制する。
        ///  `enable_log`: 非 0 で client/server のファイルログを有効にする。0 で全ログ抑制。
        ///  Unity 側のマスターログフラグから渡す。
        ///  Returns 0 on success, non-zero on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_init(int use_gpu, int enable_log);

        /// <summary>
        ///  Pump CEF message loop — no-op in IPC mode (server has its own loop).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_pump", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_pump();

        /// <summary>
        ///  Returns the number of on_paint calls (tracked per-frame reads in IPC mode).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_paint_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_paint_count();

        /// <summary>
        ///  Returns the number of pump iterations.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_pump_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_pump_count();

        /// <summary>
        ///  Shut down: send Shutdown command and wait for server to exit.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_shutdown();

        /// <summary>
        ///  NSEvent スクロールモニタを開始する。1=成功 0=失敗 (ヘッドレス等)。
        ///  macOS 以外は常に 0 (呼び出し側がフォールバックする)。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_scroll_monitor_start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_scroll_monitor_start();

        [DllImport(__DllName, EntryPoint = "cef_scroll_monitor_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_scroll_monitor_stop();

        /// <summary>
        ///  新着イベントを out に書き、件数を返す。毎フレーム呼ぶこと (リング鮮度維持)。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_scroll_monitor_poll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_scroll_monitor_poll(CefScrollEvent* @out, int max);

        /// <summary>
        ///  イベント timestamp と同一クロック (起動からの秒) の現在時刻。リサンプル基準用。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_scroll_monitor_now", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern double cef_scroll_monitor_now();

        /// <summary>
        ///  Create a browser instance via IPC.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_create_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CefUnityBrowser* cef_unity_create_browser(int width, int height, byte* url);

        /// <summary>
        ///  Destroy a browser instance.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_destroy_browser(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_load_url(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_resize(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Send a mouse move event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_move", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_move(CefUnityBrowser* handle, int x, int y, uint modifiers);

        /// <summary>
        ///  Send a mouse click event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_click", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_click(CefUnityBrowser* handle, int x, int y, uint modifiers, byte button, int mouse_up, int click_count);

        /// <summary>
        ///  Send a mouse wheel event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_wheel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_wheel(CefUnityBrowser* handle, int x, int y, uint modifiers, int delta_x, int delta_y);

        /// <summary>
        ///  Send a key event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_key_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_key_event(CefUnityBrowser* handle, byte event_type, uint modifiers, int windows_key_code, int native_key_code, ushort character, ushort unmodified_character, int is_system_key, int focus_on_editable_field);

        /// <summary>
        ///  Execute JavaScript in the browser's main frame.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_execute_javascript", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_execute_javascript(CefUnityBrowser* handle, byte* code);

        /// <summary>
        ///  Execute an editing command (copy, paste, cut, select_all, undo, redo).
        ///  command: 0=Copy, 1=Paste, 2=Cut, 3=SelectAll, 4=Undo, 5=Redo
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_edit_command", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_edit_command(CefUnityBrowser* handle, byte command);

        /// <summary>
        ///  Get the browser's current main-frame URL as UTF-8 bytes.
        ///  Returns the required buffer size including the trailing NUL terminator.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_url(CefUnityBrowser* handle, byte* buffer, int buffer_len);

        /// <summary>
        ///  Get the latest frame buffer from shared memory.
        ///  Returns 1 if a new frame is available, 0 if unchanged.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_buffer(CefUnityBrowser* handle, byte** out_buffer, int* out_width, int* out_height);

        /// <summary>
        ///  Read the IME caret rect from shared memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_ime_caret", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_get_ime_caret(CefUnityBrowser* handle, int* out_x, int* out_y, int* out_w, int* out_h);

        /// <summary>
        ///  現在の音声ストリームフォーマットを取得する。
        ///  戻り値: ストリーム再生中なら 1、停止中/音声無効なら 0。
        ///  `out_sample_rate` / `out_channels` には最新のフォーマットを書き込む
        ///  (停止中でも直近の値が残る)。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_audio_format", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_audio_format(CefUnityBrowser* handle, uint* out_sample_rate, uint* out_channels);

        /// <summary>
        ///  音声リングバッファから未読の PCM を読み出す。
        ///
        ///  `out_samples` には interleaved な f32 サンプル (LRLR... 順) を書き込む。
        ///  バッファは少なくとも `max_frames * channels` 個の f32 を保持できること
        ///  (channels は最大 [`cef_unity_ipc::AUDIO_MAX_CHANNELS`])。安全のため呼び出し側は
        ///  `max_frames * AUDIO_MAX_CHANNELS` 確保することを推奨。
        ///
        ///  `out_channels` には実際のチャネル数を書き込む。
        ///  戻り値: 実際に読み出したフレーム数 (新規データが無ければ 0)。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_read_audio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_read_audio(CefUnityBrowser* handle, float* out_samples, int max_frames, uint* out_channels);

        /// <summary>
        ///  ネイティブ音声出力を開始する。
        ///  既存の `cef_unity_read_audio` (録画 tap) とはリングカーソルが独立しており併用可。
        ///  CefAudioOutput (Unity ミキサ再生) と同時に有効にすると二重再生になる。
        ///
        ///  `target_ms`: jitter buffer の目標滞留量 (推奨 15)。
        ///  `io_frames`: CoreAudio IO バッファフレーム数 (推奨 128 ≈ 2.9ms)。0 以下は 128。
        ///  戻り値: 0=成功 (既に再生中も 0)、-1=失敗 (音声無効・フォーマット未確定・
        ///  AU 起動失敗・非対応 OS)。フォーマット未確定で失敗するため、呼び出し側は
        ///  `cef_unity_get_audio_format` が 1 を返してから呼ぶこと。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_audio_native_start", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_audio_native_start(CefUnityBrowser* handle, float target_ms, int io_frames);

        /// <summary>
        ///  ネイティブ音声出力を停止する (排水待ちして返る)。未開始なら何もしない。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_audio_native_stop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_audio_native_stop(CefUnityBrowser* handle);

        /// <summary>
        ///  ネイティブ音声出力の音量 (0.0〜)。callback 内で乗算される。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_audio_native_set_volume", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_audio_native_set_volume(CefUnityBrowser* handle, float volume);

        /// <summary>
        ///  ネイティブ音声出力の診断値を取得する。
        ///  `out_occupancy_ms`: jitter buffer の滞留量 (ms)。
        ///  `out_underrun_frames` / `out_overflow_frames`: 累積フレーム数。
        ///  戻り値: 0=再生中、-1=停止中/非対応 OS (out には書き込まない)。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_audio_native_stats", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_audio_native_stats(CefUnityBrowser* handle, float* out_occupancy_ms, ulong* out_underrun_frames, ulong* out_overflow_frames);

        /// <summary>
        ///  Destroy a browser instance (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_destroy_browser_blocking(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_load_url_blocking(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_resize_blocking(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Send a mouse move event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_move_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_move_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers);

        /// <summary>
        ///  Send a mouse click event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_click_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_click_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers, byte button, int mouse_up, int click_count);

        /// <summary>
        ///  Send a mouse wheel event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_wheel_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_wheel_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers, int delta_x, int delta_y);

        /// <summary>
        ///  Send a key event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_key_event_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_key_event_blocking(CefUnityBrowser* handle, byte event_type, uint modifiers, int windows_key_code, int native_key_code, ushort character, ushort unmodified_character, int is_system_key, int focus_on_editable_field);

        /// <summary>
        ///  Set IME composition text (preedit).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_set_composition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_set_composition(CefUnityBrowser* handle, byte* text, uint selection_start, uint selection_end);

        /// <summary>
        ///  Commit IME text (finalize composition and insert text).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_commit_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_commit_text(CefUnityBrowser* handle, byte* text);

        /// <summary>
        ///  Finish composing text (apply current composition).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_finish_composing_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_finish_composing_text(CefUnityBrowser* handle, int keep_selection);

        /// <summary>
        ///  External BeginFrame: CEF Viz Compositor に次フレームの描画許可を出す。
        ///  Unity の Update 冒頭で呼ぶ。Init 時に WindowInfo::external_begin_frame_enabled=1
        ///  が立っているブラウザに対してのみ意味を持つ。fire-and-forget。
        ///  `unity_frame` には Time.frameCount を渡す。on_accelerated_paint 経由で shm に転送され、
        ///  `cef_unity_get_accel_paint_unity_frame` で読み取ることで end-to-end の遅延フレーム数を測れる。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_external_begin_frame", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_external_begin_frame(CefUnityBrowser* handle, ulong unity_frame);

        /// <summary>
        ///  最後の on_accelerated_paint に対応する SendExternalBeginFrame 発行時の Unity frame
        ///  番号を返す。Unity 側は `Time.frameCount - 戻り値` で end-to-end の遅延フレーム数
        ///  (BeginFrame 発行から実際にテクスチャが使えるようになるまで) を計算できる。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_accel_paint_unity_frame", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_accel_paint_unity_frame(CefUnityBrowser* handle);

        /// <summary>
        ///  accelerated paint の単調増加カウンタ (accel_frame_id) を消費せずに返す。
        ///  double-pump 同期に使う: flush BeginFrame の直前にこの値を記録し、flush 後に
        ///  この値を超えるまで待てば、flush が生成した最新 paint の IOSurface が
        ///  受信ポートに届いていることが保証される (server は Mach 送信完了後に +1 する)。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_peek_accel_frame_id", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_peek_accel_frame_id(CefUnityBrowser* handle);

        /// <summary>
        ///  Cancel the current IME composition.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_cancel_composition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_cancel_composition(CefUnityBrowser* handle);

        /// <summary>
        ///  Check if a new accelerated paint frame is available via IOSurface.
        ///  Returns 1 if new info, 0 if unchanged. Writes surface_id, width, height, format to out params.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_iosurface_info", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_iosurface_info(CefUnityBrowser* handle, uint* out_surface_id, int* out_width, int* out_height, uint* out_format);

        /// <summary>
        ///  Create a Metal texture backed by an IOSurface.
        ///  Uses the system default Metal device internally.
        ///  Returns an opaque MTLTexture pointer, or null on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_create_metal_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_create_metal_texture(uint surface_id, int width, int height, uint format);

        /// <summary>
        ///  Receive the latest IOSurface from the server via Mach port and create a Metal texture.
        ///  Returns an opaque MTLTexture pointer, or null if no new frame.
        ///  The caller must release the returned texture with cef_unity_release_metal_texture.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_recv_iosurface_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_recv_iosurface_texture(int* out_width, int* out_height, uint* out_format);

        /// <summary>
        ///  Returns 1 if the Mach IOSurface port channel is connected, 0 otherwise.
        ///  CPU モード (Init で use_gpu=0) のときは常に 0 を返す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_is_iosurface_connected", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_is_iosurface_connected();

        /// <summary>
        ///  Release a Metal texture previously created by cef_unity_create_metal_texture.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_release_metal_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_release_metal_texture(void* texture);

        /// <summary>
        ///  Retrieve server logs as NUL-separated UTF-8 entries.
        ///  If buffer is null, sends GetLogs via IPC, caches result, and returns required size.
        ///  If buffer is non-null, copies cached data into buffer and clears the cache.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_logs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_logs(byte* buffer, int buffer_len);

        /// <summary>
        ///  Execute JavaScript in the browser's main frame (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_execute_javascript_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_execute_javascript_blocking(CefUnityBrowser* handle, byte* code);

        /// <summary>
        ///  Unity Native Plugin Interface のエントリポイント。Unity が DLL ロード時に呼ぶ。
        ///  IUnityGraphicsD3D11 / IUnityGraphicsD3D12v5 経由で Unity の Device を取得し保持する。
        ///  両方を試して、Unity の graphics backend に応じて生きている方が使われる。
        ///  非 Windows プラットフォームでは何もしない。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "UnityPluginLoad", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void UnityPluginLoad(void* unity_interfaces);

        /// <summary>
        ///  Unity Native Plugin Interface のアンロード。Unity が DLL アンロード時に呼ぶ。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "UnityPluginUnload", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void UnityPluginUnload();

        /// <summary>
        ///  Windows: Unity の D3D11 device に接続済みなら 1 を返す。
        ///  CPU モード (Init で use_gpu=0) のときは常に 0 を返す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_is_d3d11_connected", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_is_d3d11_connected();

        /// <summary>
        ///  Windows: Unity の D3D12 device に接続済みなら 1 を返す。
        ///  C# 側はこちらが 1 のとき `cef_unity_recv_d3d12_texture` を呼ぶ。
        ///  CPU モード (Init で use_gpu=0) のときは常に 0 を返す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_is_d3d12_connected", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_is_d3d12_connected();

        /// <summary>
        ///  Windows: 共有メモリから最新の D3D11 共有 HANDLE を読み出し、
        ///  Unity の D3D11Device で OpenSharedResource1 した ID3D11Texture2D* を返す。
        ///  新フレームが無い場合は null。
        ///
        ///  戻り値ポインタは内部で AddRef 済みのキャッシュであり、次に handle が変わるか
        ///  プラグイン unload までは Unity 側で再 AddRef せずに使ってよい。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_recv_d3d11_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_recv_d3d11_texture(CefUnityBrowser* handle, int* out_width, int* out_height, uint* out_format);

        /// <summary>
        ///  Windows: 共有メモリから最新の D3D11 共有 HANDLE を読み出し、
        ///  Unity の D3D12Device で OpenSharedHandle した ID3D12Resource* を返す。
        ///  KeyedMutex で server との排他とキャッシュコヒーレンスを取り、
        ///  初回のみ COMMON → PIXEL_SHADER_RESOURCE 状態遷移を Unity に宣言する。
        ///  新フレームが無い場合は null。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_recv_d3d12_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_recv_d3d12_texture(CefUnityBrowser* handle, int* out_width, int* out_height, uint* out_format);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CefUnityBrowser
    {
        public byte _opaque;
    }

    /// <summary>
    ///  生スクロールイベント (scroll_monitor.m / C# 側と同一レイアウト)。
    ///  phase: 0=None 1=GestureBegan 2=GestureChanged 3=GestureEnded
    ///         4=MomentumBegan 5=MomentumChanged 6=MomentumEnded 7=Cancelled
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CefScrollEvent
    {
        public double timestamp;
        public float dx;
        public float dy;
        public byte phase;
        public byte precise;
    }



}
