<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>CefUnity.Core</AssemblyName>
    <RootNamespace>CefUnity</RootNamespace>
    <DefineConstants>$(DefineConstants);CEF_UNITY_DEV_TOOLS</DefineConstants>
  </PropertyGroup>
  <Target Name="CopyToUnityPlugins" AfterTargets="Build" Condition="'$(Configuration)'=='Release'">
    <Copy SourceFiles="$(OutputPath)CefUnity.Core.dll"
          DestinationFolder="$(MSBuildThisFileDirectory)..\..\cef-unity-unityproject\Assets\CefUnity\Plugins" />
  </Target>
</Project>
