// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CefUnity
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "cef_unity_rust";





        /// <summary>
        ///  Initialize the CEF framework. Call once at app startup.
        ///  Returns 0 on success, non-zero on failure.
        ///
        ///  CEF is initialized on a dedicated background thread. The message pump
        ///  runs on that thread with ObjC exception handling to survive the
        ///  ChromeWebAppShortcutCopierMain → NSWindow crash.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_init();

        /// <summary>
        ///  No-op kept for C# API compatibility. The background thread pumps
        ///  automatically.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_pump", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_pump();

        /// <summary>
        ///  No-op. The CEF UI thread runs for the lifetime of the process because
        ///  CEF cannot be re-initialized after shutdown.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_shutdown();

        /// <summary>
        ///  Create a browser instance. Returns a handle (null on failure).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_create_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CefUnityBrowser* cef_unity_create_browser(int width, int height, byte* url);

        /// <summary>
        ///  Destroy a browser instance.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_destroy_browser(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_load_url(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_resize(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Get the latest frame buffer.
        ///  Returns 1 if a new frame is available, 0 if unchanged.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_buffer(CefUnityBrowser* handle, byte** out_buffer, int* out_width, int* out_height);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CefUnityBrowser
    {
        public byte _opaque;
    }



}
