// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CefUnity
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "cef_unity_rust";





        /// <summary>
        ///  Initialize: launch CEF server process and connect via ipc-channel.
        ///  Returns 0 on success, non-zero on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_init();

        /// <summary>
        ///  Pump CEF message loop — no-op in IPC mode (server has its own loop).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_pump", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_pump();

        /// <summary>
        ///  Returns the number of on_paint calls (tracked per-frame reads in IPC mode).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_paint_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_paint_count();

        /// <summary>
        ///  Returns the number of pump iterations.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_pump_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_pump_count();

        /// <summary>
        ///  Shut down: send Shutdown command and wait for server to exit.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_shutdown();

        /// <summary>
        ///  Create a browser instance via IPC.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_create_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CefUnityBrowser* cef_unity_create_browser(int width, int height, byte* url);

        /// <summary>
        ///  Destroy a browser instance.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_destroy_browser(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_load_url(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_resize(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Get the latest frame buffer from shared memory.
        ///  Returns 1 if a new frame is available, 0 if unchanged.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_buffer(CefUnityBrowser* handle, byte** out_buffer, int* out_width, int* out_height);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CefUnityBrowser
    {
        public byte _opaque;
    }



}
