// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CefUnity
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "cef_unity_rust";





        /// <summary>
        ///  Initialize: launch CEF server process and connect via ipc-channel.
        ///  Returns 0 on success, non-zero on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_init", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_init();

        /// <summary>
        ///  Pump CEF message loop — no-op in IPC mode (server has its own loop).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_pump", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_pump();

        /// <summary>
        ///  Returns the number of on_paint calls (tracked per-frame reads in IPC mode).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_paint_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_paint_count();

        /// <summary>
        ///  Returns the number of pump iterations.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_pump_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ulong cef_unity_get_pump_count();

        /// <summary>
        ///  Shut down: send Shutdown command and wait for server to exit.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_shutdown", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_shutdown();

        /// <summary>
        ///  Create a browser instance via IPC.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_create_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern CefUnityBrowser* cef_unity_create_browser(int width, int height, byte* url);

        /// <summary>
        ///  Destroy a browser instance.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_destroy_browser(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_load_url(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_resize(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Send a mouse move event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_move", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_move(CefUnityBrowser* handle, int x, int y, uint modifiers);

        /// <summary>
        ///  Send a mouse click event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_click", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_click(CefUnityBrowser* handle, int x, int y, uint modifiers, byte button, int mouse_up, int click_count);

        /// <summary>
        ///  Send a mouse wheel event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_wheel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_mouse_wheel(CefUnityBrowser* handle, int x, int y, uint modifiers, int delta_x, int delta_y);

        /// <summary>
        ///  Send a key event.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_key_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_send_key_event(CefUnityBrowser* handle, byte event_type, uint modifiers, int windows_key_code, int native_key_code, ushort character, ushort unmodified_character, int is_system_key, int focus_on_editable_field);

        /// <summary>
        ///  Execute JavaScript in the browser's main frame.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_execute_javascript", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_execute_javascript(CefUnityBrowser* handle, byte* code);

        /// <summary>
        ///  Execute an editing command (copy, paste, cut, select_all, undo, redo).
        ///  command: 0=Copy, 1=Paste, 2=Cut, 3=SelectAll, 4=Undo, 5=Redo
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_edit_command", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_edit_command(CefUnityBrowser* handle, byte command);

        /// <summary>
        ///  Get the browser's current main-frame URL as UTF-8 bytes.
        ///  Returns the required buffer size including the trailing NUL terminator.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_url", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_url(CefUnityBrowser* handle, byte* buffer, int buffer_len);

        /// <summary>
        ///  Get the latest frame buffer from shared memory.
        ///  Returns 1 if a new frame is available, 0 if unchanged.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_buffer(CefUnityBrowser* handle, byte** out_buffer, int* out_width, int* out_height);

        /// <summary>
        ///  Read the IME caret rect from shared memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_ime_caret", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_get_ime_caret(CefUnityBrowser* handle, int* out_x, int* out_y, int* out_w, int* out_h);

        /// <summary>
        ///  Destroy a browser instance (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_destroy_browser_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_destroy_browser_blocking(CefUnityBrowser* handle);

        /// <summary>
        ///  Load a URL in the browser (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_load_url_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_load_url_blocking(CefUnityBrowser* handle, byte* url);

        /// <summary>
        ///  Resize the browser viewport (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_resize_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_resize_blocking(CefUnityBrowser* handle, int width, int height);

        /// <summary>
        ///  Send a mouse move event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_move_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_move_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers);

        /// <summary>
        ///  Send a mouse click event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_click_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_click_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers, byte button, int mouse_up, int click_count);

        /// <summary>
        ///  Send a mouse wheel event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_mouse_wheel_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_mouse_wheel_blocking(CefUnityBrowser* handle, int x, int y, uint modifiers, int delta_x, int delta_y);

        /// <summary>
        ///  Send a key event (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_send_key_event_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_send_key_event_blocking(CefUnityBrowser* handle, byte event_type, uint modifiers, int windows_key_code, int native_key_code, ushort character, ushort unmodified_character, int is_system_key, int focus_on_editable_field);

        /// <summary>
        ///  Set IME composition text (preedit).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_set_composition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_set_composition(CefUnityBrowser* handle, byte* text, uint selection_start, uint selection_end);

        /// <summary>
        ///  Commit IME text (finalize composition and insert text).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_commit_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_commit_text(CefUnityBrowser* handle, byte* text);

        /// <summary>
        ///  Finish composing text (apply current composition).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_finish_composing_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_finish_composing_text(CefUnityBrowser* handle, int keep_selection);

        /// <summary>
        ///  Cancel the current IME composition.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_ime_cancel_composition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_ime_cancel_composition(CefUnityBrowser* handle);

        /// <summary>
        ///  Check if a new accelerated paint frame is available via IOSurface.
        ///  Returns 1 if new info, 0 if unchanged. Writes surface_id, width, height, format to out params.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_iosurface_info", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_iosurface_info(CefUnityBrowser* handle, uint* out_surface_id, int* out_width, int* out_height, uint* out_format);

        /// <summary>
        ///  Create a Metal texture backed by an IOSurface.
        ///  Uses the system default Metal device internally.
        ///  Returns an opaque MTLTexture pointer, or null on failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_create_metal_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_create_metal_texture(uint surface_id, int width, int height, uint format);

        /// <summary>
        ///  Receive the latest IOSurface from the server via Mach port and create a Metal texture.
        ///  Returns an opaque MTLTexture pointer, or null if no new frame.
        ///  The caller must release the returned texture with cef_unity_release_metal_texture.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_recv_iosurface_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_recv_iosurface_texture(int* out_width, int* out_height, uint* out_format);

        /// <summary>
        ///  Returns 1 if the Mach IOSurface port channel is connected, 0 otherwise.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_is_iosurface_connected", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_is_iosurface_connected();

        /// <summary>
        ///  Release a Metal texture previously created by cef_unity_create_metal_texture.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_release_metal_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void cef_unity_release_metal_texture(void* texture);

        /// <summary>
        ///  Retrieve server logs as NUL-separated UTF-8 entries.
        ///  If buffer is null, sends GetLogs via IPC, caches result, and returns required size.
        ///  If buffer is non-null, copies cached data into buffer and clears the cache.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_get_logs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_get_logs(byte* buffer, int buffer_len);

        /// <summary>
        ///  Execute JavaScript in the browser's main frame (blocking).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_execute_javascript_blocking", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_execute_javascript_blocking(CefUnityBrowser* handle, byte* code);

        /// <summary>
        ///  Unity Native Plugin Interface のエントリポイント。Unity が DLL ロード時に呼ぶ。
        ///  IUnityGraphicsD3D11 / IUnityGraphicsD3D12v5 経由で Unity の Device を取得し保持する。
        ///  両方を試して、Unity の graphics backend に応じて生きている方が使われる。
        ///  非 Windows プラットフォームでは何もしない。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "UnityPluginLoad", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void UnityPluginLoad(void* unity_interfaces);

        /// <summary>
        ///  Unity Native Plugin Interface のアンロード。Unity が DLL アンロード時に呼ぶ。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "UnityPluginUnload", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void UnityPluginUnload();

        /// <summary>
        ///  Windows: Unity の D3D11 device に接続済みなら 1 を返す。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_is_d3d11_connected", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_is_d3d11_connected();

        /// <summary>
        ///  Windows: Unity の D3D12 device に接続済みなら 1 を返す。
        ///  C# 側はこちらが 1 のとき `cef_unity_recv_d3d12_texture` を呼ぶ。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_is_d3d12_connected", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int cef_unity_is_d3d12_connected();

        /// <summary>
        ///  Windows: 共有メモリから最新の D3D11 共有 HANDLE を読み出し、
        ///  Unity の D3D11Device で OpenSharedResource1 した ID3D11Texture2D* を返す。
        ///  新フレームが無い場合は null。
        ///
        ///  戻り値ポインタは内部で AddRef 済みのキャッシュであり、次に handle が変わるか
        ///  プラグイン unload までは Unity 側で再 AddRef せずに使ってよい。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_recv_d3d11_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_recv_d3d11_texture(CefUnityBrowser* handle, int* out_width, int* out_height, uint* out_format);

        /// <summary>
        ///  Windows: 共有メモリから最新の D3D11 共有 HANDLE を読み出し、
        ///  Unity の D3D12Device で OpenSharedHandle した ID3D12Resource* を返す。
        ///  KeyedMutex で server との排他とキャッシュコヒーレンスを取り、
        ///  初回のみ COMMON → PIXEL_SHADER_RESOURCE 状態遷移を Unity に宣言する。
        ///  新フレームが無い場合は null。
        /// </summary>
        [DllImport(__DllName, EntryPoint = "cef_unity_recv_d3d12_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* cef_unity_recv_d3d12_texture(CefUnityBrowser* handle, int* out_width, int* out_height, uint* out_format);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct CefUnityBrowser
    {
        public byte _opaque;
    }



}
